pipelines:
  default:
    - step:
        name: Sync to GitHub
        image: atlassian/default-image:2
        script:
          - git remote add github https://$GITHUB_USERNAME:$GITHUB_TOKEN@github.com/Prescott-Data/user-app.git
          - git push github --all
          - git push github --tags